name: Deploy external

on:
  workflow_dispatch:

jobs:
  deploy:
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    runs-on: ubuntu-latest
    permissions: 
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - uses: chrnorm/deployment-action@v2.0.5
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          environment: some-env
          transient-environment: true

      - run: echo "steps.deployment.outputs.deployment_id = ${{ steps.deployment.outputs.deployment_id }}"

      # - run: sleep 15
      # - env: 
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: python3 deployment_status_updater.py "${{ steps.deployment.outputs.deployment_id }}"
        
          