name: printenv

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  printenv:
    name: Printenv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Printenv
        run: printenv