name: Update GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1